=== ah-Elsharkawy/Attendance-system/userScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="NameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:pattern value="[A-Za-z ]+"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- <xs:simpleType name="IDType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="50"/>
		</xs:restriction>
	</xs:simpleType> -->
	<xs:simpleType name="RoleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Admin"/>
			<xs:enumeration value="Teacher"/>
			<xs:enumeration value="Student"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EmailType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PassType">
		<xs:restriction base="xs:string">
			<xs:minLength value="6"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<!--<xs:simpleType name="ClassType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Lab1"/>
			<xs:enumeration value="Lab2"/>
			<xs:enumeration value="Lab3"/>
		</xs:restriction>
	</xs:simpleType>-->
	<xs:element name="Name" type="NameType"/>
	<xs:element name="ID" type="xs:integer"/>
	<xs:element name="Role" type="RoleType"/>
	<xs:element name="Email" type="EmailType"/>
	<xs:element name="Password" type="PassType"/>
	<xs:element name="Class" type="xs:string"/>
	<xs:group name="userGroup">
		<xs:sequence>
			<xs:element ref="Name"/>
			<xs:element ref="ID"/>
			<xs:element ref="Role"/>
			<xs:element ref="Email"/>
			<xs:element ref="Password"/>
			<xs:element ref="Class" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="UserComplex">
		<xs:group ref="userGroup"/>
	</xs:complexType>
	<xs:element name="User" type="UserComplex"/>
	<xs:group name="UsersGroup">
		<xs:sequence>
			<xs:element ref="User" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="UsersComplex">
		<xs:group ref="UsersGroup"/>
	</xs:complexType>
	<xs:element name="Users" type="UsersComplex"/>
	
</xs:schema>

=== ah-Elsharkawy/Attendance-system/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userScheme.xsd">
  <User>
    <Name>Admin User</Name>
    <ID>1</ID>
    <Role>Admin</Role>
    <Email>admin@admin.com</Email>
    <Password>admin123</Password>
  </User>
  <User>
    <Name>Teacher One</Name>
    <ID>2</ID>
    <Role>Teacher</Role>
    <Email>teacher1@gmail.com</Email>
    <Password>teacher123</Password>
  </User>
  <User>
    <Name>Student One</Name>
    <ID>3</ID>
    <Role>Student</Role>
    <Email>student1@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>Student Two</Name>
    <ID>4</ID>
    <Role>Student</Role>
    <Email>student2@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab2</Class>
  </User>
  <User>
    <Name>Student Three</Name>
    <ID>5</ID>
    <Role>Student</Role>
    <Email>student3@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab3</Class>
  </User>
  <User>
    <Name>Student Four</Name>
    <ID>12</ID>
    <Role>Student</Role>
    <Email>student4@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>Student Five</Name>
    <ID>13</ID>
    <Role>Student</Role>
    <Email>student5@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab2</Class>
  </User>
  <User>
    <Name>Student Six</Name>
    <ID>14</ID>
    <Role>Student</Role>
    <Email>student6@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab3</Class>
  </User>
  <User>
    <Name>Student Seven</Name>
    <ID>15</ID>
    <Role>Student</Role>
    <Email>student7@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>Student Eight</Name>
    <ID>16</ID>
    <Role>Student</Role>
    <Email>student8@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab2</Class>
  </User>
  <User>
    <Name>Student Nine</Name>
    <ID>17</ID>
    <Role>Student</Role>
    <Email>student9@gmail.com</Email>
    <Password>student123</Password>
    <Class>Lab3</Class>
  </User>
  <User>
    <Name>New User</Name>
    <ID>18</ID>
    <Role>Student</Role>
    <Email>newuser@gmail.com</Email>
    <Password>newuser123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>New User</Name>
    <ID>19</ID>
    <Role>Student</Role>
    <Email>newuser@gmail.com</Email>
    <Password>newuser123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>New User</Name>
    <ID>19</ID>
    <Role>Student</Role>
    <Email>newuser@gmail.com</Email>
    <Password>newuser123</Password>
    <Class>Lab1</Class>
  </User>
  <User>
    <Name>New User</Name>
    <ID>19</ID>
    <Role>Student</Role>
    <Email>newuser@gmail.com</Email>
    <Password>newuser123</Password>
    <Class>Lab1</Class>
  </User>
</Users>
