=== ah-Elsharkawy/Attendance-system/attendanceSystem/Data/dataScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- types -->
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:pattern value="[A-Za-z ]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passType">
		<xs:restriction base="xs:string">
			<xs:minLength value="8"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="roleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="admin"/>
			<xs:enumeration value="teacher"/>
			<xs:enumeration value="student"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="present"/>
			<xs:enumeration value="absent"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PD"/>
			<xs:enumeration value="OS"/>
			<xs:enumeration value="AI"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Id" type="xs:integer"/>
	<xs:element name="Name" type="nameType"/>
	<xs:element name="Email" type="emailType"/>
	<xs:element name="Password" type="passType"/>
	<xs:element name="Role" type="roleType"/>
	<xs:element name="class" type="classType"/>
	<xs:element name="sClass" type="classType"/>
	<xs:element name="Date" type="xs:date"/>
	<xs:element name="Status" type="statusType"/>
	<xs:group name="recordGroup">
		<xs:sequence>
			<xs:element ref="Date"/>
			<xs:element ref="Status"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="recordType">
		<xs:group ref="recordGroup"/>
	</xs:complexType>
	<xs:complexType name="attendType">
		<xs:sequence>
			<xs:element name="Record" type="recordType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="classesType">
		<xs:sequence>
			<xs:element ref="class" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="userInfo">
		<xs:sequence>
			<xs:element ref="Id"/>
			<xs:element ref="Name"/>
			<xs:element ref="Email"/>
			<xs:element ref="Password"/>
			<xs:element ref="Role"/>
			<xs:element name="Classes" type="classesType" minOccurs="0"/>
			<xs:element name="Attendance" type="attendType" minOccurs="0"/>
			<xs:element ref="sClass" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="userType">
		<xs:group ref="userInfo"/>
	</xs:complexType>
	<!--
	<xs:group name="userInfo2">
		<xs:sequence>
			<xs:element ref="id"/>
			<xs:element ref="name"/>
			<xs:element ref="email"/>
			<xs:element ref="password"/>
			<xs:element ref="role"/>
			<xs:element name="classes" type="classesType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="userType2">
		<xs:group ref="userInfo2"/>
	</xs:complexType>
	
	<xs:complexType name="studentType" >
		<xs:sequence>
			<xs:group ref="userInfo2"/>
			<xs:element name="attendance" type="attendType"/>
			<xs:element ref="sClass"/>
		</xs:sequence>
	</xs:complexType>
	-->
	<xs:complexType name="usersType">
		<xs:sequence>
			<xs:element name="user" type="userType" maxOccurs="unbounded"/>
			<!--
				<xs:element name="student" type="studentType" maxOccurs="unbounded" minOccurs="0"></xs:element>
				-->
		</xs:sequence>
	</xs:complexType>
	<xs:element name="users" type="usersType"/>
</xs:schema>

=== ah-Elsharkawy/Attendance-system/attendanceSystem/Data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataScheme.xsd">
  <user>
    <Id>1</Id>
    <Name>ahmed</Name>
    <Email>a@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Admin</Role>
  </user>
  <user>
    <Id>2</Id>
    <Name>mohamed</Name>
    <Email>n@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Teacher</Role>
    <Classes>
      <class>PD</class>
      <class>OS</class>
      <class>AI</class>
    </Classes>
  </user>
  <user>
    <Id>3</Id>
    <Name>mahmoud</Name>
    <Email>m@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Teacher</Role>
    <Classes>
      <class>PD</class>
      <class>OS</class>
      <class>AI</class>
    </Classes>
  </user>
  <user>
    <Id>4</Id>
    <Name>ahmed</Name>
    <Email>b@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>5</Id>
    <Name>ahmed</Name>
    <Email>c@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>6</Id>
    <Name>ahmed</Name>
    <Email>d@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>7</Id>
    <Name>ahmed</Name>
    <Email>e@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>8</Id>
    <Name>ahmed</Name>
    <Email>f@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>9</Id>
    <Name>ahmed</Name>
    <Email>g@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>10</Id>
    <Name>ahmed</Name>
    <Email>h@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>11</Id>
    <Name>ahmed</Name>
    <Email>i@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>absent</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>12</Id>
    <Name>ahmed</Name>
    <Email>j@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-02</Date>
        <Status>present</Status>
      </Record>
      <Record>
        <Date>2024-02-03</Date>
        <Status>present</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>12</Id>
    <Name>ahmed</Name>
    <Email>j@gmail.com</Email>
    <Password>12345678</Password>
    <Role>Student</Role>
    <Attendance>
      <Record>
        <Date>2024-02-03</Date>
        <Status>present</Status>
      </Record>
    </Attendance>
    <SClass>PD</SClass>
  </user>
  <user>
    <Id>db0ee21c-dc55-47f9-9546-30bf0a0453a2</Id>
    <Name>addTeacher</Name>
    <Email>test@add.com</Email>
    <Password>1233456</Password>
    <Role>Teacher</Role>
    <Classes>
      <class>OS</class>
      <class>PD</class>
    </Classes>
  </user>
  <user>
    <Id>e88fa615-bb6c-4973-b34b-e6c63f059c80</Id>
    <Name>newTeacher</Name>
    <Email>add@teacher.com</Email>
    <Password>12345678</Password>
    <Role>Teacher</Role>
    <Classes>
      <class>AI</class>
    </Classes>
  </user>
  <user>
    <Id>774392e3-f582-4499-94a5-9fd26aec1685</Id>
    <Name>addStudent</Name>
    <Email>add@student.com</Email>
    <Password>s123568</Password>
    <Role>Student</Role>
    <SClass>OS</SClass>
  </user>
</users>
